export type AlertStatus = 'vert' | 'orange' | 'rouge' | 'gris'

export interface KPI {
  id: string
  pilier: string
  nom: string
  definition: string
  unite: string
  valeur: string
  annee: number
  source: string
  url: string
  seuil_vert: string | null
  seuil_orange: string | null
  seuil_rouge: string | null
  recommandation: string
  priorite: string
  statut: AlertStatus
}

export const KPIS: KPI[] = [
  {
    id: 'KPI-01',
    pilier: 'Contexte',
    nom: 'Population totale',
    definition: "Nombre total d'habitants en Tunisie",
    unite: 'Nombre',
    valeur: '12,3 millions',
    annee: 2025,
    source: 'DataReportal',
    url: 'https://datareportal.com/reports/digital-2025-tunisia',
    seuil_vert: null,
    seuil_orange: null,
    seuil_rouge: null,
    recommandation: 'Utiliser comme base de calcul des ratios',
    priorite: 'Haute',
    statut: 'gris',
  },
  {
    id: 'KPI-02',
    pilier: 'Infrastructures',
    nom: 'Utilisateurs Internet',
    definition: "Nombre estimé d'utilisateurs d'Internet en Tunisie",
    unite: 'Nombre',
    valeur: '10,5 millions',
    annee: 2025,
    source: 'DataReportal',
    url: 'https://datareportal.com/reports/digital-2025-tunisia',
    seuil_vert: 'Taux supérieur à 85 % population',
    seuil_orange: 'Taux entre 70 % et 85 % population',
    seuil_rouge: 'Taux inférieur à 70 % population',
    recommandation: "Renforcer l'inclusion numérique",
    priorite: 'Très haute',
    statut: 'vert',
  },
  {
    id: 'KPI-03',
    pilier: 'Infrastructures',
    nom: 'Connexions mobiles / population',
    definition: 'Nombre de connexions mobiles rapporté à la population',
    unite: '% population',
    valeur: '128 %',
    annee: 2025,
    source: 'DataReportal',
    url: 'https://datareportal.com/reports/digital-2025-tunisia',
    seuil_vert: 'Supérieur à 100 %',
    seuil_orange: 'Entre 80 % et 100 %',
    seuil_rouge: 'Inférieur à 80 %',
    recommandation: 'Développer les services publics et financiers sur mobile',
    priorite: 'Haute',
    statut: 'vert',
  },
  {
    id: 'KPI-04',
    pilier: 'Infrastructures',
    nom: 'Débit mobile médian',
    definition: 'Vitesse médiane de téléchargement sur réseau mobile',
    unite: 'Mbps',
    valeur: '26,56',
    annee: 2025,
    source: 'Ookla / DataReportal',
    url: 'https://datareportal.com/reports/digital-2025-tunisia',
    seuil_vert: 'Supérieur à 50 Mbps',
    seuil_orange: 'Entre 20 et 50 Mbps',
    seuil_rouge: 'Inférieur à 20 Mbps',
    recommandation: 'Améliorer la qualité du réseau mobile',
    priorite: 'Haute',
    statut: 'orange',
  },
  {
    id: 'KPI-05',
    pilier: 'Infrastructures',
    nom: 'Débit fixe médian',
    definition: 'Vitesse médiane de téléchargement sur réseau fixe',
    unite: 'Mbps',
    valeur: '11,55',
    annee: 2025,
    source: 'Ookla / DataReportal',
    url: 'https://datareportal.com/reports/digital-2025-tunisia',
    seuil_vert: 'Supérieur à 30 Mbps',
    seuil_orange: 'Entre 15 et 30 Mbps',
    seuil_rouge: 'Inférieur à 15 Mbps',
    recommandation: 'Accélérer les investissements fibre et haut débit fixe',
    priorite: 'Très haute',
    statut: 'rouge',
  },
  {
    id: 'KPI-06',
    pilier: 'Capital humain',
    nom: 'Human Capital Index',
    definition: "Sous-indice du capital humain dans l'EGDI",
    unite: 'Score /1',
    valeur: '0,8032',
    annee: 2024,
    source: 'UN DESA',
    url: 'https://publicadministration.un.org/egovkb/en-us/Data-Center',
    seuil_vert: 'Supérieur à 0,75',
    seuil_orange: 'Entre 0,60 et 0,75',
    seuil_rouge: 'Inférieur à 0,60',
    recommandation: 'Renforcer les filières numériques et IA',
    priorite: 'Haute',
    statut: 'vert',
  },
  {
    id: 'KPI-07',
    pilier: 'Economie productive',
    nom: 'Rang écosystème startup',
    definition: "Classement mondial de l'écosystème startup tunisien",
    unite: 'Rang',
    valeur: '82e',
    annee: 2025,
    source: 'StartupBlink',
    url: 'https://www.startupblink.com/startup-ecosystem/tunisia',
    seuil_vert: 'Top 60',
    seuil_orange: 'Entre 60 et 100',
    seuil_rouge: 'Supérieur à 100',
    recommandation: 'Renforcer le financement et la visibilité internationale',
    priorite: 'Haute',
    statut: 'orange',
  },
  {
    id: 'KPI-08',
    pilier: 'Economie productive',
    nom: "Valeur de l'écosystème tech",
    definition: "Valeur estimée de l'écosystème technologique tunisien",
    unite: 'USD',
    valeur: '241,5 M USD',
    annee: 2025,
    source: 'Startup Genome',
    url: 'https://startupgenome.com/reports/global-startup-ecosystem-report-2025',
    seuil_vert: 'Croissance supérieure à 20 %',
    seuil_orange: 'Croissance entre 5 % et 20 %',
    seuil_rouge: 'Croissance inférieure à 5 %',
    recommandation: 'Soutenir les startups à fort potentiel',
    priorite: 'Moyenne',
    statut: 'orange',
  },
  {
    id: 'KPI-09',
    pilier: 'Fintech',
    nom: 'Paiements mobiles',
    definition: "Nombre d'opérations de paiement mobile",
    unite: 'Nombre',
    valeur: '8,4 millions',
    annee: 2025,
    source: 'BCT',
    url: 'https://www.bct.gov.tn/',
    seuil_vert: 'Croissance supérieure à 30 %',
    seuil_orange: 'Croissance entre 10 % et 30 %',
    seuil_rouge: 'Croissance inférieure à 10 %',
    recommandation: "Accélérer l'inclusion financière numérique",
    priorite: 'Très haute',
    statut: 'vert',
  },
  {
    id: 'KPI-10',
    pilier: 'Fintech',
    nom: 'Portefeuilles numériques actifs',
    definition: 'Nombre de portefeuilles électroniques actifs',
    unite: 'Nombre',
    valeur: '815 000',
    annee: 2025,
    source: 'BCT',
    url: 'https://www.bct.gov.tn/',
    seuil_vert: 'Croissance supérieure à 30 %',
    seuil_orange: 'Croissance entre 10 % et 30 %',
    seuil_rouge: 'Croissance inférieure à 10 %',
    recommandation: "Développer les usages wallet et l'interopérabilité",
    priorite: 'Très haute',
    statut: 'vert',
  },
  {
    id: 'KPI-11',
    pilier: 'E-gouvernement',
    nom: 'EGDI',
    definition: "Indice de développement de l'e-gouvernement",
    unite: 'Score /1',
    valeur: '0,6935',
    annee: 2024,
    source: 'UN DESA',
    url: 'https://publicadministration.un.org/egovkb/en-us/Data-Center',
    seuil_vert: 'Supérieur à 0,75',
    seuil_orange: 'Entre 0,60 et 0,75',
    seuil_rouge: 'Inférieur à 0,60',
    recommandation: "Renforcer l'e-gouvernement",
    priorite: 'Très haute',
    statut: 'orange',
  },
  {
    id: 'KPI-12',
    pilier: 'E-gouvernement',
    nom: 'OSI',
    definition: 'Indice des services publics en ligne',
    unite: 'Score /1',
    valeur: '0,5951',
    annee: 2024,
    source: 'UN DESA',
    url: 'https://publicadministration.un.org/egovkb/en-us/Data-Center',
    seuil_vert: 'Supérieur à 0,70',
    seuil_orange: 'Entre 0,50 et 0,70',
    seuil_rouge: 'Inférieur à 0,50',
    recommandation: 'Industrialiser les services publics en ligne',
    priorite: 'Très haute',
    statut: 'orange',
  },
  {
    id: 'KPI-13',
    pilier: 'E-gouvernement',
    nom: 'Abonnés E-Houwiya',
    definition: "Nombre d'abonnés à l'identité numérique mobile tunisienne",
    unite: 'Nombre',
    valeur: '200 000',
    annee: 2025,
    source: 'ID Tech Wire',
    url: 'https://idtechwire.com/tunisias-mobile-id-subscribers-reach-200000/',
    seuil_vert: 'Croissance supérieure à 30 %',
    seuil_orange: 'Croissance entre 10 % et 30 %',
    seuil_rouge: 'Croissance inférieure à 10 %',
    recommandation: "Généraliser l'identité numérique dans les services publics",
    priorite: 'Moyenne',
    statut: 'rouge',
  },
  {
    id: 'KPI-14',
    pilier: 'Gouvernance',
    nom: 'Global Cybersecurity Index',
    definition: "Niveau de maturité cybersécurité selon l'UIT",
    unite: 'Tier',
    valeur: 'Tier 3',
    annee: 2024,
    source: 'UIT',
    url: 'https://www.itu.int/en/ITU-D/Cybersecurity/Pages/global-cybersecurity-index.aspx',
    seuil_vert: 'Tier 1 ou 2',
    seuil_orange: 'Tier 3',
    seuil_rouge: 'Tier 4 ou 5',
    recommandation: 'Renforcer la cybersécurité nationale',
    priorite: 'Très haute',
    statut: 'orange',
  },
  {
    id: 'KPI-15',
    pilier: 'Gouvernance',
    nom: 'Année loi données personnelles',
    definition: 'Année de référence du cadre juridique tunisien sur les données personnelles',
    unite: 'Année',
    valeur: '2004',
    annee: 2025,
    source: 'JORT',
    url: 'https://www.iort.gov.tn/',
    seuil_vert: 'Loi postérieure à 2018',
    seuil_orange: 'Loi entre 2010 et 2018',
    seuil_rouge: 'Loi antérieure à 2010',
    recommandation: 'Mettre à jour la législation sur les données personnelles',
    priorite: 'Très haute',
    statut: 'rouge',
  },
]

export const PILIERS = [...new Set(KPIS.map(k => k.pilier))]

export const HIGHLIGHT_KPIS = ['KPI-02', 'KPI-03', 'KPI-06']

export const NEWS = [
  {
    id: 1,
    titre: "Lancement du RENT 2025",
    date: "1er juin 2025",
    extrait: "La plateforme officielle du rapport annuel de l'économie numérique tunisienne est en ligne.",
  },
  {
    id: 2,
    titre: "Tunisie : hausse des paiements mobiles de 25 %",
    date: "15 mai 2025",
    extrait: "Selon la BCT, les opérations de paiement mobile ont atteint 8,4 millions en 2025.",
  },
  {
    id: 3,
    titre: "Nouvelle stratégie e-gouvernement 2025–2030",
    date: "10 avril 2025",
    extrait: "Le gouvernement annonce un plan ambitieux de digitalisation des services publics.",
  },
]

export const ARTICLES = [
  {
    id: 1,
    titre: "Pourquoi l'écosystème startup tunisien monte en puissance",
    date: "Mars 2025",
    extrait: "Avec un 82e rang mondial, la Tunisie consolide sa position sur la carte mondiale de l'entrepreneuriat tech.",
  },
  {
    id: 2,
    titre: "L'identité numérique E-Houwiya : défis et opportunités",
    date: "Février 2025",
    extrait: "200 000 abonnés en 2025 — comment accélérer l'adoption de l'identité numérique mobile tunisienne.",
  },
  {
    id: 3,
    titre: "Le rôle de l'IA dans le futur rapport RENT",
    date: "Janvier 2025",
    extrait: "L'intelligence artificielle au service de l'analyse économique numérique et de la génération de rapports.",
  },
]